### ISSUE TITLE
Not all stock icons appear in GActions in toolbar on Ubuntu 14.04

### ISSUE THREAD

**Issue by davidcsterratt** [jverzani/gWidgets2RGtk2#14]
Hello again,

this is a really minor bug, not a showstopper at all, and perhaps is specific to my setup.

Not all the icons that should be available (according  http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html) are showing up in GActions, as demonstrated below.
```
library(gWidgets2)
options(guiToolkit="RGtk2")

h.cb <- function(h, ...) {}

g.win <- gwindow("Test gtoolbar()")
g.open <- gaction("Open", icon="open", handler=h.cb) # Has icon
g.run <-   gaction("Run", icon="system-run", handler=h.cb) # Doesn't have icon
g.media <- gaction("Media", icon="media-record", handler=h.cb) # Has icon
g.toolbar <- gtoolbar(list(open=g.open, g.run, g.media),
                      container=g.win, style="both")
```

**Comment by jverzani** [comment]
Well it isn't just you, I don't get the "run" icon either on my virtual Ubuntu test environment. Wish I knew why, but not really sure where to look for this.

**Comment by davidcsterratt** [comment]
It seems that anything that is in the list at https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GtkStockItem works. You just have to remove `GTK_STOCK_` from the macro name, and put the result in lower case. e.g.  `GTK_STOCK_EXECUTE` -> `execute`. This gives me the run button I was looking for.

However, this method of referring to icons is deprecated - I'm not sure what the alternative method is, and I suppose you probably want to hold off moving to the newer calls for as long as possible, to avoid having to check for the GTK version number in the code.

**Comment by jverzani** [comment]
Thanks, this will be a good reference. The worry about deprecated methods is apt, but as far as I know the RGtk2 package is only for Gtk2 and not Gtk3, so it is already more or less feature frozen, so maybe that isn't such a concern until there is a RGtk3.
