### ISSUE TITLE
Release 1.0.4 to CRAN?

### ISSUE THREAD

**Issue by davidcsterratt** [jverzani/gWidgets2RGtk2#16]
I was giving a very basic talk on gWidgets2 yesterday (https://github.com/davidcsterratt/edinbr-gWidgets), and got myself thoroughly confused when, on one Linux machine, the following code gave an error (`Error in plot.new() : figure margins too large`) and did not produce the expected plot:
```
library(gWidgets2)
options(guiToolkit="RGtk2")
library(cairoDevice) 
win <- gwindow("Hello World, the next generation")
group <- ggroup(horizontal=FALSE, container=win)
g.d <- ggraphics(container=group, width=600, height=600)
d <- dev.cur()
obj <- gbutton("Plot", container = group,
               handler=function(h, ...) {
                 x <- rnorm(50)
                 plot(density(x, adjust=1, kernel="gaussian"))
                 rug(x)
               })
```
It turns out that, in preparation fro the talk, I had installed gWidgets2RGtk 1.0.3 on this machine. On another machine with the latest github version  there was no problem. Upgrading to the latest github version (1.0.4) on the problematic machine fixed the problem. I'd suggest pushing the github version to CRAN, unless there are good reasons not to.

**Comment by jverzani** [comment]
Thanks for the reminder! Just did this today, so should be available soon.
