### ISSUE TITLE
File Browser `selectdir` not using `intitial.dir`

### ISSUE THREAD

**Issue by tmelliott** [jverzani/gWidgets2RGtk2#17]
Hi John,

In this section
https://github.com/jverzani/gWidgets2RGtk2/blob/master/R/gfile.R#L72-L84
there's no case for `type = "selectdir"`. I assume one of the "open" cases is supposed to be it? 

Anyway, I've fixed on my fork by adding an additional `else if` so there's no urgency for a fix, just a general FYI.

Cheers!

**Comment by jverzani** [comment]
Can you put in a pull request? I'd be happy to incorporate your change. Thanks.

**Comment by jverzani** [comment]
Closing. It seems to be working now. Please re-open if I am missing something.
